### ISSUE TITLE
Nevergrad is outdated

### ISSUE THREAD

**Issue by Corwinpro** [rdturnermtl/bbo_challenge_starter_kit#2]
The specified `nevergrad` version (`nevergrad==0.1.4`) is a bit outdated.

Would it be possible to bump up the `nevergrad` version to `0.4.x`? This would require some changes in the example code, as the API has changed since.

UPD: I guess, this can also be done by specifying a `nevergrad` version in the requirements.txt. Please close the issue if this approach to "upgrade" a package is supported.

**Comment by rdturnermtl** [comment]
I will add this to the server side issue list for an upgrade to the nevergrad version. Since, adding nevergrad to the requirements list is a workable solution for now, I will close this here.
