### ISSUE TITLE
How to suggest new dependency

### ISSUE THREAD

**Issue by Alaya-in-Matrix** [rdturnermtl/bbo_challenge_starter_kit#3]
In my BO implementation, there are some dependencies not listed in the environment.txt, how shoud I suggest adding new dependencies?

**Comment by rdturnermtl** [comment]
We have been assuming requests would go to the contact e-mail: `info@bbochallenge.com`.

They can also be placed here, too.

**Comment by ntienvu** [comment]
Hi @Alaya-in-Matrix, have you solved the issue with dependencies yet ?
We are currently suffering this problem.

**Comment by Alaya-in-Matrix** [comment]
> Hi @Alaya-in-Matrix, have you solved the issue with dependencies yet ?
> We are currently suffering this problem.
> 
> I follow exactly the instruction to place all of the dependencies in the same folder.
> The script runs well locally: using run_local.sh
> 
> However, whenever I submit it online, it returns an error without explicitly returning anything.

Yeah, I sent an email to `info@bbochallenge.com` to ask about the dependency issue. I was told that I can put my own dependencies in the `requirement.txt` and they would be automatically installed by pip.

**Comment by Alaya-in-Matrix** [comment]
> Hi @Alaya-in-Matrix, have you solved the issue with dependencies yet ?
> We are currently suffering this problem.
> 
> I follow exactly the instruction to place all of the dependencies in the same folder.
> The script runs well locally: using run_local.sh
> 
> However, whenever I submit it online, it returns an error without explicitly returning anything.

I'm now also suffering from the dependency issue :(

**Comment by ntienvu** [comment]
I emailed them `info@bbochallenge.com` for this dependency problem, but havenot hearded back yet.

**Comment by rdturnermtl** [comment]
If there are errors as a result of a dependency issue please copy-and-paste the task ID here, or e-mail it to `info@bbochallenge.com`.

We can check if there is a pip install incompatibility.

**Comment by rdturnermtl** [comment]
@ntienvu @Alaya-in-Matrix Are there still issues with proposing a new dependency. Can this issue be closed?

**Comment by Alaya-in-Matrix** [comment]
@rdturnermtl I've solved the problem by manually building *.whl files from *.tar.gz files, it's OK for me to close this issue.
